--#####################################################################################
--AUTOGENERATED HYPR CONFIG.
--PLEASE EDIT THIS FILE ACCORDING TO THE WIKI INSTRUCTIONS.
--OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
--#######################################################################################

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki
-- autogenerated = 1 # remove this line to remove the warning

-- █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█
-- █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄

-- See https://wiki.hyprland.org/Configuring/Monitors/


hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "auto",
})

-- █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
-- █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more
-- Execute your favorite apps at launch

local scrPath = "~/.config/hypr/scripts"

-- █▀▀ █▄░█ █░█
-- ██▄ █░▀█ ▀▄▀

-- Some default env vars.

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_STYLE_OVERRIDE", "kvantum")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("MOZ_ENABLE_WAYLAND", "1")

-- █ █▄░█ █▀█ █░█ ▀█▀
-- █ █░▀█ █▀▀ █▄█ ░█░

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

hl.device({
    name = "epic mouse V1",
    sensitivity = -0.5,
})

hl.gesture({
    fingers = 3,
    direction = "left",
    action = "workspace",
    workspace_name = "m-1",
})
hl.gesture({
    fingers = 3,
    direction = "right",
    action = "workspace",
    workspace_name = "m+1",
})

-- Split configuration modules.
require("animations")
require("keybindings")
require("windowrules")
require("themes.common")
require("themes.theme")
require("themes.colors")
require("monitors")
require("userprefs")

hl.config({
    input = {
        kb_layout = "us,ru",
        follow_mouse = 1,
        touchpad = {
            natural_scroll = false,
        },
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
        force_no_accel = 1,
    },
    -- Example per-device config
    -- See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
    -- See https://wiki.hyprland.org/Configuring/Variables/ for more
    -- █░░ ▄▀█ █▄█ █▀█ █░█ ▀█▀ █▀
    -- █▄▄ █▀█ ░█░ █▄█ █▄█ ░█░ ▄█
    -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    dwindle = {
        preserve_split = true, -- you probably want this
    },
    -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    master = {
        new_status = "master",
    },
    -- █▀▄▀█ █ █▀ █▀▀
    -- █░▀░█ █ ▄█ █▄▄
    -- See https://wiki.hyprland.org/Configuring/Variables/ for more
    misc = {
        vrr = 2,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        force_default_wallpaper = 0,
    },
    -- █▀ █▀█ █░█ █▀█ █▀▀ █▀▀
    -- ▄█ █▄█ █▄█ █▀▄ █▄▄ ██▄
    -- Source a file (multi-file configs)
    -- userprefs is loaded last so it can override defaults.
})

hl.on("hyprland.start", function()
    hl.exec_cmd("hypridle")
    hl.exec_cmd(scrPath .. "/resetxdgportal.sh")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("dbus-update-activation-environment --systemd GNOME_KEYRING_CONTROL SSH_AUTH_SOCK")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user start xdg-desktop-portal")
    hl.exec_cmd("hyprpolkitagent")
    hl.exec_cmd("waybar")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("dunst")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd(scrPath .. "/swwwallpaper.sh")
    hl.exec_cmd(scrPath .. "/batterynotify.sh")
    hl.exec_cmd("tmux setenv -g HYPRLAND_INSTANCE_SIGNATURE \"$HYPRLAND_INSTANCE_SIGNATURE\"")
    hl.exec_cmd("rm -rf /run/user/*/gdm/* 2>/dev/null; rm -rf /var/cache/gdm/* 2>/dev/null")
end)
