# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█


# Set your monitor configuration here
# See https://wiki.hyprland.org/Configuring/Monitors/

# Specific 2k monitor
monitor = DP-8, 2560x1440@144, 0x0, 1, bitdepth, 10, vrr, 2

# Fallback for any other monitor (e.g., when the 2k is not connected)
# This will apply to any monitor that is not explicitly configured above.
monitor = , 1920x1080@60, auto, 1

misc {
    vrr = 2
}
