# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█


# Set your monitor configuration here
# See https://wiki.hyprland.org/Configuring/Monitors/

# Main 2k monitor
monitor = desc:Microstep MSI MAG274QRF CA8A220B01269, 2560x1440@144, 0x0, 1, bitdepth, 10, vrr, 1

# Fallback for any other monitor (e.g., when the 2k is not connected)
# This will apply to any monitor that is not explicitly configured above.
monitor = , preferred, auto, 1
